# Generated by Django 5.0.3 on 2024-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_token', models.CharField(default='', max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_photo', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('preferred_roles', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('portfolio_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('github_link', models.URLField()),
                ('anyother_link', models.URLField(blank=True)),
                ('exp_title', models.CharField(max_length=255)),
                ('exp_company', models.CharField(max_length=255)),
                ('exp_description', models.CharField(max_length=255)),
                ('project_title', models.CharField(max_length=255)),
                ('project_link', models.URLField()),
                ('project_description', models.CharField(max_length=255)),
                ('skills', models.TextField()),
            ],
        ),
    ]
