# Generated by Django 5.0.3 on 2024-03-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='project_description',
            field=models.CharField(max_length=500),
        ),
    ]
