# Generated by Django 5.0.3 on 2024-03-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('remote_policy', models.CharField(max_length=10)),
            ],
        ),
    ]
