# Generated by Django 5.0.3 on 2024-03-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_remote_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_mailid',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
