# Generated by Django 5.0.3 on 2024-03-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_company_mailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('applicant_ids', models.TextField()),
            ],
        ),
    ]
